apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-dns-dns
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["services"]
    resourceNames: ["kube-dns"]
    verbs: ["get"]
