{{- $providername := include "external-dns.providername" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "external-dns.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "external-dns.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.deploymentStrategy | nindent 4 }}
  {{- with .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "external-dns.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.secretConfiguration.enabled .Values.podAnnotations }}
      annotations:
        {{- if .Values.secretConfiguration.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      {{- if hasKey .Values "automountServiceAccountToken" }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "external-dns.serviceAccountName" . }}
      {{- with .Values.shareProcessNamespace }}
      shareProcessNamespace: {{ . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: external-dns
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "external-dns.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - --log-level={{ .Values.logLevel }}
            - --log-format={{ .Values.logFormat }}
            - --interval={{ .Values.interval }}
            {{- if .Values.triggerLoopOnEvent }}
            - --events
            {{- end }}
            {{- range .Values.sources }}
            - --source={{ . }}
            {{- end }}
            - --policy={{ .Values.policy }}
            - --registry={{ .Values.registry }}
            {{- if .Values.txtOwnerId }}
            - --txt-owner-id={{ .Values.txtOwnerId }}
            {{- end }}
            {{- if .Values.txtPrefix }}
            - --txt-prefix={{ .Values.txtPrefix }}
            {{- end }}
            {{- if and (eq .Values.txtPrefix "") (ne .Values.txtSuffix "") }}
            - --txt-suffix={{ .Values.txtSuffix }}
            {{- end }}
            {{- if .Values.namespaced }}
            - --namespace={{ .Release.Namespace }}
            {{- end }}
            {{- range .Values.domainFilters }}
            - --domain-filter={{ . }}
            {{- end }}
            {{- if contains "/" $providername }}
            - --provider=webhook
            {{- else }}
            - --provider={{ tpl $providername $ }}
            {{- end }}
          {{- range .Values.extraArgs }}
            - {{ tpl . $ }}
          {{- end }}
          ports:
            - name: http
              protocol: TCP
              containerPort: 7979
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- if or .Values.secretConfiguration.mountPath .Values.extraVolumeMounts }}
          volumeMounts:
            {{- if .Values.secretConfiguration.mountPath }}
            - name: secrets
              mountPath: {{ tpl .Values.secretConfiguration.mountPath $ }}
            {{- with .Values.secretConfiguration.subPath }}
              subPath: {{ tpl . $ }}
            {{- end }}
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if contains "/" $providername }}
        - name: provider
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ tpl $providername $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.provider.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
          {{- range .Values.provider.args }}
            - {{ tpl . $ }}
          {{- end }}
          ports:
            - name: provider-metrics
              protocol: TCP
              containerPort: 8080
          livenessProbe:
            {{- toYaml .Values.provider.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.provider.readinessProbe | nindent 12 }}
          {{- if or .Values.provider.secretConfiguration.mountPath .Values.provider.extraVolumeMounts }}
          volumeMounts:
            {{- if .Values.provider.secretConfiguration.mountPath }}
            - name: secrets
              mountPath: {{ tpl .Values.provider.secretConfiguration.mountPath $ }}
            {{- with .Values.provider.secretConfiguration.subPath }}
              subPath: {{ tpl . $ }}
            {{- end }}
            {{- end }}
            {{- with .Values.provider.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.provider.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- if or .Values.secretConfiguration.mountPath (and (contains "/" $providername) .Values.provider.secretConfiguration.mountPath) .Values.extraVolumes }}
      volumes:
        {{- if or .Values.secretConfiguration.mountPath (and (contains "/" $providername) .Values.provider.secretConfiguration.mountPath) }}
        - name: secrets
          secret:
            secretName: {{ include "external-dns.fullname" . }}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
