{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "external-dns.fullname" . }}-dns
  namespace: kube-system
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    resourceNames: ["kube-dns"]
    verbs: ["get"]
{{- end }}
